import { useEffect, useMemo, useState } from "react";
import { ReactFlow, Background, Controls } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import "./styles.css";
type Lead={leadId:number;company:string;contact:string;title:string;opportunityScore:number;whyNow:string;nextBestAction:string;dataConfidence:number;scoreBreakdown:any;signals:any[];corporateRelationships:string[]};
const API=import.meta.env.VITE_API_URL||"http://localhost:8080/api";
const demo:Lead[]=Array.from({length:200},(_,i)=>{const s=i<32?94:i<106?78:i<157?62:45;return{leadId:i+1,company:["Apex Commerce","Apex Payments","Northstar Labs","CloudWorks","Vertex Systems"][i%5],contact:"Decision Maker "+(i+1),title:i%2?"VP Engineering":"CTO",opportunityScore:s,whyNow:s>=85?"Strong growth and technology fit indicate a timely opportunity.":s>=70?"Relevant fit signals make this account worth targeted outreach.":"Monitor for a stronger trigger.",nextBestAction:s>=85?"Contact decision maker today.":s>=70?"Send personalized outreach within 48 hours.":"Add to nurture.",dataConfidence:92,scoreBreakdown:{revenuePotential:20,growth:18,technologyFit:17,decisionMaker:15,industryFit:14,corporateRelationship:i<3?6:0,dataConfidence:10},signals:[{type:"COMPANY_GROWTH",weight:18,description:"Growth and hiring activity create a timing trigger."},{type:"TECHNOLOGY_FIT",weight:17,description:"Technology environment aligns with the target profile."}],corporateRelationships:i<3?["SUBSIDIARY → Apex Holdings"]:[]}}});
const band=(s:number)=>s>=85?"HOT":s>=70?"GOOD":s>=55?"NURTURE":"LOW";
export default function App(){
 const[leads,setLeads]=useState<Lead[]>([]); const[selected,setSelected]=useState<Lead|null>(null); const[view,setView]=useState("dashboard"); const[search,setSearch]=useState(""); const[priority,setPriority]=useState("ALL"); const[demoMode,setDemoMode]=useState(false);
 useEffect(()=>{fetch(API+"/leads").then(r=>r.ok?r.json():Promise.reject()).then(setLeads).catch(()=>{setLeads(demo);setDemoMode(true)})},[]);
 const shown=useMemo(()=>leads.filter(l=>(priority==="ALL"||band(l.opportunityScore)===priority)&&l.company.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.opportunityScore-a.opportunityScore),[leads,search,priority]);
 const open=(l:Lead)=>{setSelected(l);setView("intelligence");fetch(API+"/leads/"+l.leadId+"/intelligence").then(r=>r.ok?r.json():null).then(x=>x&&setSelected(x)).catch(()=>{})};
 const counts={HOT:leads.filter(x=>x.opportunityScore>=85).length,GOOD:leads.filter(x=>x.opportunityScore>=70&&x.opportunityScore<85).length,NURTURE:leads.filter(x=>x.opportunityScore>=55&&x.opportunityScore<70).length,LOW:leads.filter(x=>x.opportunityScore<55).length};
 return <div className="app"><header><div className="brand"><div className="logo">OI</div><div><b>Opportunity & Account Intelligence</b><small>Turn 200 leads into opportunities worth pursuing</small></div></div><span className="status">{demoMode?"DEMO DATA":"LIVE DATA"}</span></header><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>Dashboard</button><button className={view==="accounts"?"active":""} onClick={()=>setView("accounts")}>Corporate Intelligence</button>{selected&&<button className={view==="intelligence"?"active":""} onClick={()=>setView("intelligence")}>Lead Intelligence</button>}</nav>{view==="dashboard"?<Dashboard leads={shown} all={leads} counts={counts} search={search} setSearch={setSearch} priority={priority} setPriority={setPriority} open={open}/>:view==="intelligence"&&selected?<Intelligence lead={selected}/>:<Accounts leads={leads}/>}</div>
}
function Dashboard(p:any){return <main><section className="hero"><div><label>OPPORTUNITY COMMAND CENTER</label><h1>Know which lead to contact first — and why now.</h1><p>Explainable prioritization across revenue, growth, technology, decision makers, relationships and confidence.</p></div><button className="cta" onClick={()=>location.reload()}>Analyze Opportunities</button></section><div className="metrics">{Object.entries({ANALYZED:p.all.length,...p.counts}).map(([k,v])=><div className="metric" key={k}><label>{k}</label><strong>{Number(v)}</strong></div>)}</div><section className="panel"><div className="toolbar"><h2>Top opportunities</h2><div><input placeholder="Search company" value={p.search} onChange={(e)=>p.setSearch(e.target.value)}/><select value={p.priority} onChange={(e)=>p.setPriority(e.target.value)}><option>ALL</option><option>HOT</option><option>GOOD</option><option>NURTURE</option><option>LOW</option></select></div></div><table><thead><tr><th>COMPANY</th><th>SCORE</th><th>PRIORITY</th><th>WHY NOW</th><th>NEXT BEST ACTION</th></tr></thead><tbody>{p.leads.slice(0,50).map((l:Lead)=><tr key={l.leadId} onClick={()=>p.open(l)}><td><b>{l.company}</b><small>{l.contact} · {l.title}</small></td><td className="score">{l.opportunityScore}</td><td><em className={band(l.opportunityScore)}>{band(l.opportunityScore)}</em></td><td>{l.whyNow}</td><td>{l.nextBestAction}</td></tr>)}</tbody></table></section></main>}
function Intelligence({lead}:any){const b=lead.scoreBreakdown;const rows=[["Revenue Potential",b.revenuePotential,20],["Growth",b.growth,18],["Technology Fit",b.technologyFit,17],["Decision Maker",b.decisionMaker,15],["Industry Fit",b.industryFit,14],["Corporate Relationship",b.corporateRelationship,6],["Data Confidence",b.dataConfidence,10]];return <main><section className="hero"><div><label>LEAD INTELLIGENCE</label><h1>{lead.company}</h1><p>{lead.contact} · {lead.title}</p></div><div className="big">{lead.opportunityScore}<small>/100</small></div></section><div className="columns"><section className="panel"><label>WHY NOW</label><h2>{lead.whyNow}</h2><div className="action"><label>NEXT BEST ACTION</label><b>{lead.nextBestAction}</b></div><label>BUYING SIGNALS</label>{lead.signals.map((s:any)=><div className="signal" key={s.type}><b>{s.type.replaceAll("_"," ")}</b><span>+{s.weight}</span><small>{s.description}</small></div>)}</section><section className="panel"><label>SCORE BREAKDOWN</label>{rows.map(r=><div className="scoreRow" key={String(r[0])}><span>{r[0]} <b>{r[1]}/{r[2]}</b></span><div><i style={{width:(Number(r[1])/Number(r[2])*100)+"%"}}/></div></div>)}<div className="confidence">DATA CONFIDENCE {lead.dataConfidence}%</div></section></div></main>}
function Accounts({leads}:{leads:Lead[]}){const related=leads.filter(l=>l.corporateRelationships.length).slice(0,3);const nodes=[{id:"p",position:{x:300,y:30},data:{label:"APEX HOLDINGS"}},...related.map((l,i)=>({id:String(l.leadId),position:{x:60+i*230,y:190},data:{label:l.company+" · "+l.opportunityScore}}))];const edges=related.map(l=>({id:"e"+l.leadId,source:"p",target:String(l.leadId),label:"SUBSIDIARY"}));return <main><section className="hero"><div><label>CORPORATE INTELLIGENCE</label><h1>See the account, not just the lead.</h1><p>Relationship context turns isolated opportunities into account-level strategy.</p></div></section><div className="columns"><section className="panel graph"><ReactFlow nodes={nodes} edges={edges} fitView><Background/><Controls/></ReactFlow></section><section className="panel"><label>ACCOUNT INSIGHT</label><h2>3 related opportunities detected</h2><div className="accountScore">94</div><p>Recommended strategy</p><b>Account-level outreach</b>{related.map(l=><div className="related" key={l.leadId}><span>{l.company}</span><b>{l.opportunityScore}</b></div>)}</section></div></main>}